# Site settings
title: "About Me"
description: "?"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Thad Benjaponpitak"
resume_title:                   "Nice to meet you!"
resume_contact_email:
  "blead010@gmail.com"

# "yes": display the email contact button
# "no": display an "I'm not looking for work" message
# anything else: display nothing
resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_interests:       true
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    false
resume_section_footer:          false

# Resume social links
resume_social_links:
  resume_github_url:            "https://github.com/blead"
  resume_twitter_url:           "http://twitter.com/blead_"
  # resume_dribbble_url:          ""
  # resume_facebook_url:          ""
  # resume_linkedin_url:          ""
  # resume_instagram_url:         ""
  # resume_website_url:           ""

# Design settings
resume_theme:                   default
